import { Component, Input } from '@angular/core';
import { BadgeAtom, BadgeType } from '@brejcha13320/design-system-bootstrap';
import { Musica } from '../../interfaces/musica.interface';

/**
 * Tabla que presenta canciones y distingue sus géneros con badges.
 */
@Component({
  selector: 'app-musica-table',
  templateUrl: './musica-table.component.html',
  imports: [BadgeAtom],
})
export class MusicaTableComponent {
  @Input() musica: Musica[] = [];

  generoMap: Record<string, BadgeType> = {
    "Acid House": 'primary',
    "Acid Jazz": 'warning',
    "Acid Rock": 'danger',
    "Acoustic": 'success',
    "Acoustic Blues": 'warning',
    "Afro-Pop": 'primary',
    "Afrobeat": 'warning',
    "Alt-Rock": 'danger',
    "Alternative": 'success',
    "Ambient": 'success',
    "American Trad Rock": 'danger',
    "Americana": 'success',
    "Anime": 'success',
    "Arena Rock": 'danger',
    "Art-Rock": 'danger',
    "Avant-Garde": 'success',
    "Avant-Punk": 'danger',
    "Baladas y Boleros": 'success',
    "Barbershop": 'success',
    "Baroque": 'success',
    "Bebop": 'warning',
    "Big Band": 'warning',
    "Black Metal": 'danger',
    "Blue Note": 'success',
    "Bluegrass": 'success',
    "Blues": 'warning',
    "Boogaloo": 'warning',
    "Bop": 'warning',
    "Bossa Nova": 'warning',
    "Bounce": 'success',
    "Brazilian Funk": 'warning',
    "Breakbeat": 'primary',
    "Britpop": 'primary',
    "CCM": 'success',
    "Cajun": 'success',
    "Cantopop": 'primary',
    "Celtic": 'success',
    "Celtic Folk": 'success',
    "Chamber Music": 'success',
    "Chant": 'success',
    "Chanukah": 'success',
    "Chicago Blues": 'warning',
    "Chicago House": 'primary',
    "Chicano": 'success',
    "Children’s Music": 'success',
    "Chill": 'success',
    "Choral": 'success',
    "Christian": 'success',
    "Christmas": 'success',
    "Classical": 'success',
    "Club": 'primary',
    "College Rock": 'danger',
    "Conjunto": 'warning',
    "Cool Jazz": 'warning',
    "Country": 'success',
    "Crunk": 'primary',
    "Dance": 'primary',
    "Dancehall": 'primary',
    "Death Metal": 'danger',
    "Deep House": 'primary',
    "Delta Blues": 'warning',
    "Detroit Techno": 'primary',
    "Dirty South": 'success',
    "Disco": 'primary',
    "Disney": 'success',
    "Dixieland": 'success',
    "Doo-wop": 'success',
    "Downtempo": 'success',
    "Dream Pop": 'primary',
    "Drill": 'primary',
    "Drinking Songs": 'success',
    "Drone": 'success',
    "Drum'n'bass": 'success',
    "Dub": 'primary',
    "Dubstep": 'primary',
    "EDM": 'primary',
    "Early Music": 'success',
    "East Coast Rap": 'primary',
    "Easter": 'success',
    "Easy Listening": 'success',
    "Eclectic": 'success',
    "Electric Blues": 'warning',
    "Electro": 'primary',
    "Electronic": 'primary',
    "Electronica": 'primary',
    "Emo": 'danger',
    "Enka": 'success',
    "Environmental": 'success',
    "Ethio-jazz": 'warning',
    "Experimental": 'success',
    "Experimental Rock": 'danger',
    "Flamenco": 'warning',
    "Folk": 'success',
    "Folk-Rock": 'danger',
    "Forro": 'warning',
    "French Pop": 'primary',
    "Funk": 'warning',
    "Fusion": 'success',
    "Gangsta Rap": 'primary',
    "Garage": 'primary',
    "German Folk": 'success',
    "German Pop": 'primary',
    "Glam Rock": 'danger',
    "Gospel": 'success',
    "Goth": 'danger',
    "Grime": 'success',
    "Grindcore": 'danger',
    "Groove": 'success',
    "Grunge": 'danger',
    "Hair Metal": 'danger',
    "Halloween": 'success',
    "Happy": 'success',
    "Hard Bop": 'warning',
    "Hard Dance": 'primary',
    "Hard Rock": 'danger',
    "Hardcore": 'danger',
    "Hardcore Punk": 'danger',
    "Hardcore Rap": 'danger',
    "Hardstyle": 'success',
    "Healing": 'success',
    "Heavy Metal": 'danger',
    "High Classical": 'success',
    "Hip Hop": 'success',
    "Holiday": 'success',
    "Honky Tonk": 'success',
    "House": 'primary',
    "IDM": 'success',
    "Impressionist": 'success',
    "Indie": 'success',
    "Industrial": 'danger',
    "Instrumental": 'success',
    "J-Dance": 'primary',
    "J-Idol": 'primary',
    "J-Pop": 'primary',
    "J-Punk": 'danger',
    "J-Rock": 'danger',
    "J-Ska": 'warning',
    "J-Synth": 'primary',
    "Jackin House": 'primary',
    "Jam Bands": 'success',
    "Japanese Pop": 'primary',
    "Jazz": 'warning',
    "Jungle": 'primary',
    "K-Pop": 'primary',
    "Karaoke": 'primary',
    "Kayokyoku": 'success',
    "Kids": 'success',
    "Kitsch": 'primary',
    "Klezmer": 'success',
    "Krautrock": 'danger',
    "Latin": 'warning',
    "Latin Jazz": 'warning',
    "Latin Rap": 'warning',
    "Local": 'success',
    "Lounge": 'success',
    "Lullabies": 'success',
    "MPB": 'success',
    "Mainstream Jazz": 'warning',
    "Malay": 'success',
    "Mandopop": 'primary',
    "March": 'success',
    "Mariachi": 'warning',
    "Mawwal": 'warning',
    "Medieval": 'success',
    "Meditation": 'success',
    "Metal": 'danger',
    "Metalcore": 'danger',
    "Minimal Techno": 'primary',
    "Minimalism": 'success',
    "Modern": 'success',
    "Motown": 'success',
    "Mugham": 'success',
    "Musicals": 'success',
    "Musique Concrète": 'success',
    "Nature": 'success',
    "Neo-Soul": 'warning',
    "Nerdcore": 'success',
    "New Acoustic": 'success',
    "New Age": 'success',
    "New Mex": 'success',
    "New Wave": 'success',
    "No Wave": 'success',
    "Noise": 'danger',
    "Nordic": 'success',
    "Novelty": 'success',
    "OPM": 'primary',
    "Oi!": 'success',
    "Old School Rap": 'primary',
    "Opera": 'success',
    "Orchestral": 'success',
    "Original Score": 'success',
    "Outlaw Country": 'success',
    "Pagode": 'warning',
    "Party": 'primary',
    "Piano": 'success',
    "Polka": 'success',
    "Pop": 'primary',
    "Pop Film": 'primary',
    "Pop Latino": 'warning',
    "Post Dubstep": 'primary',
    "Power Pop": 'primary',
    "Praise & Worship": 'success',
    "Progressive House": 'primary',
    "Progressive Rock": 'danger',
    "Proto-punk": 'danger',
    "Psych Rock": 'danger',
    "Psychedelic": 'success',
    "Punk": 'danger',
    "Punk Rock": 'danger',
    "Qawwali": 'warning',
    "Quiet Storm": 'success',
    "R&B": 'warning',
    "Ragtime": 'success',
    "Rainy Day": 'success',
    "Rap": 'primary',
    "Reggae": 'warning',
    "Reggaeton": 'warning',
    "Regional Mexicano": 'success',
    "Relaxation": 'success',
    "Renaissance": 'success',
    "Retro": 'success',
    "Rock": 'danger',
    "Rockabilly": 'danger',
    "Rocksteady": 'danger',
    "Romance": 'success',
    "Romantic": 'success',
    "Roots Reggae": 'warning',
    "Roots Rock": 'danger',
    "SKA": 'warning',
    "Sad": 'success',
    "Salsa": 'warning',
    "Samba": 'warning',
    "Second Line": 'success',
    "Sertanejo": 'warning',
    "Shaabi": 'warning',
    "Shoegaze": 'danger',
    "Sleep": 'success',
    "Smooth Jazz": 'warning',
    "Soft Rock": 'danger',
    "Soul": 'warning',
    "Soundtrack": 'success',
    "Southern Gospel": 'success',
    "Southern Rock": 'danger',
    "Space Rock": 'danger',
    "Stage And Screen": 'success',
    "Steampunk": 'danger',
    "Summer": 'success',
    "Surf": 'success',
    "Swamp Pop": 'primary',
    "Swing": 'warning',
    "Synth Pop": 'primary',
    "Tango": 'success',
    "Techno": 'primary',
    "Teen Pop": 'primary',
    "Tejano": 'warning',
    "Tex-Mex": 'warning',
    "Thanksgiving": 'success',
    "Traditional": 'success',
    "Trance": 'primary',
    "Trip Hop": 'success',
    "Tropical": 'success',
    "Underground Rap": 'primary',
    "Urban": 'primary',
    "Urban Cowboy": 'primary',
    "West Coast Rap": 'primary',
    "Western Swing": 'warning',
    "World": 'success',
    "Worldbeat": 'success',
    "Zydeco": 'success',
  };
}
